// Generated by CoffeeScript 1.6.3
var airDir, airServiceDir, cp, fs, path, rootDir;

cp = require('child_process');

path = require('path');

fs = require('fs');

module.exports.npmUpdate = function() {
  return cp.exec('npm update', function(error, stdout, stderr) {
    return console.log('finish updating npm modules.');
  });
};

module.exports.npmInstall = function() {
  return cp.exec('npm install', function(error, stdout, stderr) {
    return console.log('finish installing npm modules.');
  });
};

console.log('current directory is: ' + __dirname);

rootDir = __dirname;

airServiceDir = path.join(rootDir, 'AiRService');

process.chdir(airServiceDir);

if (fs.existsSync('node_modules')) {
  this.npmUpdate();
} else {
  this.npmInstall();
}

airDir = path.join(rootDir, 'AiR');

process.chdir(airDir);

if (fs.existsSync('node_modules')) {
  this.npmUpdate();
} else {
  this.npmInstall();
}
