// Generated by CoffeeScript 1.6.3
module.exports.LoadTestCard = function(req, res) {
  var cardJson;
  cardJson = {
    id: req.params.id,
    name: '34970A',
    description: 'Test Card for 34970A'
  };
  return res.send(cardJson);
};

module.exports.SearchTestCardByModel = function(req, res) {
  var cardJson;
  cardJson = {
    id: '9898',
    name: 'Test Card',
    model: '34970A',
    description: 'Test Card for 34970A'
  };
  return res.send(cardJson);
};
