// Generated by CoffeeScript 1.6.3
var data, express, service;

express = require('express');

service = express();

data = require('./AiRData');

service.get('/', function(req, res) {
  return res.send('AiR RESTFul Service');
});

service.get('/TestCard/:id', data.LoadTestCard);

service.get('/SearchTestCardByModel/:modelNumber', data.SearchTestCardByModel);

service.use(express.bodyParser());

service.use(express.methodOverride());

service.use(express["static"](__dirname + '/public'));

service.use(function(err, req, res, next) {
  console.error(err.stack);
  return res.send(500, 'Something broke!');
});

service.listen(8808);

console.log('AiR RESTFul Service is listening on port 8808.');
